all_actions = {'slice', 'heat', 'cool', 'pick', 'place', 'clean'}

all_objs = {'apple',
            'baseboard',
            'book',
            'bottle',
            'bowl',
            'bread',
            'butterknife',
            'cabinet',
            'cellphone',
            'chair',
            'clock',
            'coffee machine',
            'countertop',
            'credit card',
            'cube',
            'cup',
            'dining table',
            'dish sponge',
            'dishwasher',
            'drawer',
            'egg',
            'faucet',
            'floor',
            'fork',
            'fridge',
            'garbage bag',
            'garbage can',
            'houseplant',
            'kettle',
            'knife',
            'ladle',
            'lettuce',
            'microwave',
            'mirror',
            'mug',
            'oven',
            'pan',
            'pen',
            'pencil',
            'pepper shaker',
            'plate',
            'pot',
            'potato',
            'room',
            'safe',
            'salt shaker',
            'shelf',
            'side table',
            'sink',
            'sink cabinet',
            'soap bottle',
            'spatula',
            'sphere',
            'spoon',
            'spray bottle',
            'statue',
            'stool',
            'stove',
            'stove burner',
            'stoveknob',
            'toaster',
            'tomato',
            'cabinet',
            'vase',
            'wine bottle'}
